### ISSUE TITLE
Prony's method gives an average magnitude response of 0dB

### ISSUE THREAD

**Issue by orchidas** [jatinchowdhury18/audio_dspy#5]
Hi Jatin, we are using your library for some filter fitting. @Matteo-Scerbo is using it and noticed that warped prony module produces filter responses with an average magnitude of 0dB. Is it something that is built into Prony's method, or is it another issue?

**Comment by jatinchowdhury18** [comment]
Hi Orchi,

Thanks for catching this! The Prony's method functions were normalizing the impulse responses before everything else. That should be fixed with #6.
